apiVersion: v1
kind: Service
metadata:
    name: {{ template "thischart.fullname" . }}
    labels:
        app: {{ template "thischart.name" . }}
        chart: {{ template "thischart.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    type: ClusterIP
    ports:
        - name: http
          port: {{ .Values.webuiapi.server.port }}
          protocol: TCP
        - name: jmx
          port: 9010
          protocol: TCP
    selector:
        app: {{ template "thischart.name" . }}
        release: {{ .Release.Name }}
