version: '3.3'
services:
  keycloak-console:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: keycloak-console
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS: '-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/test-realm.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./test-realm.json
        target: /tmp/test-realm.json

  kafdrop-console:
    image: 'obsidiandynamics/kafdrop'
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka-console:29092
      - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
    depends_on:
      - kafka-console

  kafka-console:
    image: obsidiandynamics/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-console:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT=6000
      - KAFKA_RESTART_ATTEMPTS=10
      - KAFKA_RESTART_DELAY=5
      - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0
