environment: local
namespace: ubirch-dev
image:
  tag: latest # set to your local image tag if needed

# settings for ingest
webuiapi:
  noHost: true
  ingestFQDN: localhost
  kafkaURL: "kafka.core-dev.svc.cluster.local:9092"
  core:
    timeToWaitDevices: 5
  keycloak:
    server:
      url: "http://localhost:8080/auth"
      realm: "master"
      username: "admin"
      password: "admin"
      clientId: "admin-cli"
    jwt: """{"kid":"0AaUvzQhEljiSfwM1EHOFiY-ot7gpMkE6Ae5wvAtWRQ","kty":"EC","alg":"ES256","use":"sig","crv":"P-256","x":"WviSnOUu2h_iHsIkmAOlPW9Ej7qIIeRz-QxK_XhSJIk","y":"0dRaPC2pZ7PECGQItGqEVwzoxc-tGnBTLf3NSU-IM48"}"""
  server:
    port: 8081

redis:
  masterURL: "redis-stable-master.core-dev.svc.cluster.local:6379"
  slaveURL: "redis-stable-slave.core-dev.svc.cluster.local:6379"


ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-dev"
    certmanager.k8s.io/acme-dns01-provider: "dev-dns"
    kubernetes.io/ingress.allow-http: "false"
  path: /
  hosts:
    - niomon.dev.ubirch.com
  tls:
    - secretName: niomon-dev-ubirch-com-certificate
      hosts:
        - niomon.dev.ubirch.com
