environment: demo
namespace: ubirch-demo

image:
  repository: ubirch/web-admin-api-server
  tag: latest # set to your local image tag if needed

# settings for ingest
webuiapi:
  noHost: true
  core:
    timeToWaitDevices: 20
  keycloak:
    server:
      url: "http://keycloak-http.core-demo/auth"
      realm: "master"
      clientId: "admin-cli"
    realmName: "ubirch-default-realm"
    jsonConfKeyCloak: '{ "realm": "ubirch-default-realm", "auth-server-url": "https://id.demo.ubirch.com/auth", "ssl-required": "external", "resource": "ubirch-device-access", "verify-token-audience": true, "credentials": { "secret": "**********" }, "confidential-port": 0, "policy-enforcer": {} }'
  server:
    port: 8081
    baseUrl: "/ubirch-web-ui/api"
    swaggerPath: "/usr/share/service/swagger"
    scalatra:
      environment: "deployment"
  janus:
    hosts: "janusgraph.core-demo"
    port: 8182
    connectionPool:
      reconnectInterval: 500
      maxWaitForConnection: 6000
  app:
    version: "v1"



ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-demo"
    certmanager.k8s.io/acme-dns01-provider: "demo-dns-demo-ubirch-com"
    kubernetes.io/ingress.allow-http: "false"
  path: /
  hosts:
    - api.console.demo.ubirch.com
  tls:
    - secretName: api-console-demo-ubirch-com-certificate
      hosts:
        - api.console.demo.ubirch.com
