environment: ubirch-demo
namespace: ubirch-demo

image:
  repository: ubirch/web-admin-api-server
  tag: latest # set to your local image tag if needed

# settings for ingest
webuiapi:
  noHost: true
  kafkaURL: "kafka.core-demo:9092"
  core:
    timeToWaitDevices: 20
  keycloak:
    server:
      url: "http://keycloak-http.core-demo/auth"
      realm: "master"
      clientId: "admin-cli"
    jwk: '{ "kid": "UQtb1kDbUECc85hkijc0m6Pcl63EWKitUWFCt-xDHK8", "kty": "EC", "alg": "ES256", "use": "sig", "crv": "P-256", "x": "IPo05BB3H7Mw5U2N7F7kXGV2iOQEWX1up6D_U2bGSG8", "y": "K-8JxCihuSQiW4LrAb3vfkE4mFrEaBcx_KeMpRzblg0" }'
    jsonConfKeyCloak: '{ "realm": "ubirch-default-realm", "auth-server-url": "https://id.demo.ubirch.com/auth", "ssl-required": "external", "resource": "ubirch-device-access", "verify-token-audience": true, "credentials": { "secret": "**********" }, "confidential-port": 0, "policy-enforcer": {} }'
  server:
    port: 8081
    baseUrl: "/ubirch-web-ui/api"
    swaggerPath: "/usr/share/service/swagger"
    scalatra:
      environment: "deployment"
  janus:
    hosts: "janusgraph.core-demo"
    port: 8182
    connectionPool:
      reconnectInterval: 500
      maxWaitForConnection: 6000
  app:
    version: "v1"

redis:
  masterURL: "redis-stable-master.core-demo:6379"
  slaveURL: "redis-stable-slave.core-demo:6379"


ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-demo"
    certmanager.k8s.io/acme-dns01-provider: "demo-dns-demo-ubirch-com"
    kubernetes.io/ingress.allow-http: "false"
  path: /
  hosts:
    - api.console.demo.ubirch.com
  tls:
    - secretName: api-console-demo-ubirch-com-certificate
      hosts:
        - api.console.demo.ubirch.com

imagePullSecrets:
- name: trackleregistrykey-trackle-service
